name: test

on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: Swatinem/rust-cache@v2

      - name: "Check commit message for :partying_face: emoji"
        run: git log -1 --pretty=%B | grep -qE "(:partying_face:|🥳)"

      - name: Prevent excessively long commit messages
        run: (( "$(git log -1 --pretty=%s | wc -c)" <= 50 ))

      - name: cargo test
        run: cargo test --all-features

      - name: rustfmt
        run: cargo fmt --all -- --check

      - name: clippy
        run: cargo clippy --all --all-features --tests -- -D warnings
